In [261]:
import pandas as pd
import numpy as np

In [262]:
import sys
sys.path.append('../')

In [263]:
def GetPosition (array):
    if isinstance(array,np.ndarray):
        if array.__contains__('C'):
            return 'C'
        if array.__contains__('3B'):
            return '3B'
        if array.__contains__('2B'):
            return '2B'
        if array.__contains__('SS'):
            return 'SS'
        if array.__contains__('1B'):
            return '1B'
        if array.__contains__('OF'):
            return 'OF'
        else:
            return 'Util'
    else: 
        return 'Util'

In [264]:
atcpit=pd.read_json('https://www.fangraphs.com/api/projections?stats=pit&type=atc')
atcbat=pd.read_json('https://www.fangraphs.com/api/projections?stats=bat&type=atc')

In [265]:
atcbat

,Team,ShortName,G,AB,PA,H,1B,2B,3B,HR,...,ADP,Pos,minpos,UPURL,teamid,League,PlayerName,xMLBAMID,playerids,playerid
0,NYY,Yankees,144.9460,511.8710,637.1380,148.5080,76.22220,24.69210,1.008210,46.58520,...,1.850000,0.370861,OF,/players/aaron-judge/15640/stats/batting,9,AL,Aaron Judge,592450,15640,15640
1,KCR,Royals,151.4330,598.9770,660.3630,174.4240,102.95600,36.72000,6.257720,28.49000,...,3.100000,0.025316,SS,/players/bobby-witt-jr/25764/stats/batting,7,AL,Bobby Witt Jr.,677951,25764,25764
2,LAD,Dodgers,148.3860,558.8900,659.8270,158.2230,79.61940,27.19000,5.114730,46.29930,...,1.260000,0.918605,DH,/players/shohei-ohtani/19755/stats/batting,22,NL,Shohei Ohtani,660271,19755,19755
3,NYM,Mets,154.5980,543.8930,677.6950,148.6610,84.16020,24.86700,1.005500,38.62780,...,4.600000,0.018750,OF,/players/juan-soto/20123/stats/batting,25,NL,Juan Soto,665742,20123,20123
4,BAL,Orioles,152.5590,581.3360,659.3560,156.7990,93.46520,32.81950,4.197670,26.31650,...,12.310000,0.052288,SS,/players/gunnar-henderson/26289/stats/batting,2,AL,Gunnar Henderson,683002,26289,26289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,CIN,Reds,25.7053,83.5565,89.4294,19.8554,14.04760,2.91753,0.104427,2.78584,...,999.000000,0.000000,1B,/players/christian-encarnacion-strand/30011/st...,18,NL,Christian Encarnacion-Strand,687952,30011,30011
624,COL,Rockies,60.9278,207.6330,228.0380,51.9231,34.49750,10.54880,1.385180,5.49164,...,747.179993,0.111111,1B/OF,/players/troy-johnston/26143/stats/batting,19,NL,Troy Johnston,687859,26143,26143
625,KCR,Royals,31.1324,96.3296,107.9920,21.0277,13.62080,4.30266,0.794284,2.30997,...,999.000000,0.012195,OF,/players/john-rave/26284/stats/batting,7,AL,John Rave,670231,26284,26284
626,HOU,Astros,18.4386,60.7253,68.4107,12.9504,8.00483,2.43190,0.452595,2.06112,...,999.000000,0.000000,2B,/players/brice-matthews/33280/stats/batting,21,AL,Brice Matthews,694728,33280,33280
627,MIA,Marlins,20.0111,74.6882,80.4315,17.3608,11.93010,2.99226,0.088148,2.35029,...,999.000000,0.000000,1B/3B,/players/deyvison-de-los-santos/sa3015168/stat...,20,NL,Deyvison De Los Santos,691277,sa3015168,sa3015168

In [266]:
import pybaseball
positions = pybaseball.fielding_stats(2025, qual=0)
positions['Pos']=positions['Pos'].replace(['LF','CF','RF'],'OF')
positions_unique=positions.loc[(positions['G']>=10) | (positions['GS']>=5)].groupby('IDfg')['Pos'].unique()

In [267]:
positions

,IDfg,Season,Name,Team,Pos,G,GS,Inn,PO,A,...,60-90%,# 60-90%,90-100%,# 90-100%,rSZ,rCERA,rTS,FRM,OAA,Range
0,27478,2025,Patrick Bailey,SFG,C,132,114,1029.2,1013,57,...,NaN,NaN,NaN,NaN,14,4.0,NaN,21.0,NaN,NaN
1,22581,2025,Alejandro Kirk,TOR,C,118,111,965.1,968,35,...,NaN,NaN,NaN,NaN,9,-4.0,NaN,11.8,NaN,NaN
2,25764,2025,Bobby Witt Jr.,KCR,SS,154,153,1340.0,186,382,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,24.0,18.0
3,21534,2025,Cal Raleigh,SEA,C,121,119,1072.0,1060,42,...,NaN,NaN,NaN,NaN,6,-2.0,NaN,11.1,NaN,NaN
4,27479,2025,Masyn Winn,STL,SS,129,127,1107.2,163,335,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,21.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2294,35324,2025,Shinnosuke Ogasawara,WSN,P,23,2,38.2,1,5,...,NaN,NaN,NaN,NaN,0,NaN,NaN,-0.3,NaN,NaN
2295,35325,2025,Ryan Johnson,LAA,P,14,0,14.2,1,2,...,NaN,NaN,NaN,NaN,0,NaN,NaN,-0.2,NaN,NaN
2296,35333,2025,Chase Burns,CIN,P,13,8,43.1,1,5,...,NaN,NaN,NaN,NaN,0,NaN,NaN,-0.4,NaN,NaN
2297,35456,2025,Trey Yesavage,TOR,P,3,3,14.0,1,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0.1,NaN,NaN
2298,35466,2025,Payton Tolle,BOS,P,7,3,16.1,0,1,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN

In [268]:
positions_unique.index=positions_unique.index.map(str)

In [269]:
hittersmean=pd.merge(atcbat,positions_unique,how='left',left_on='playerids',right_index=True)

hittersmean['OBPOnTeam'] = (hittersmean['PA']*hittersmean['OBP']+2037.4)/(hittersmean['PA']+6100)
hittersmean['SLGOnTeam'] = (hittersmean['AB']*hittersmean['SLG']+2420)/(hittersmean['AB']+5500)
hittersmean['OPSValue'] = (hittersmean['OBPOnTeam']+hittersmean['SLGOnTeam']-.774)/.006

hittersmean['AVGValue'] = ((hittersmean['H']+1768)/(hittersmean['AB']+6100)-.267)/.0024
hittersmean['value'] = hittersmean['OPSValue']+(hittersmean['R']/8.92+hittersmean['HR']/7.5+hittersmean['RBI']/8.92+hittersmean['SB']/7.0)

hittersmean['Pos']=hittersmean['Pos_y']

hittersmean['BestPos']=hittersmean['Pos'].apply(GetPosition)

hittersmean['rank']=hittersmean.groupby('BestPos')['value'].rank(ascending=False)
hittersmean['utilrank']=hittersmean['value'].rank(ascending=False)

ValueC = hittersmean.loc[hittersmean['BestPos']=='C']['value'].nlargest(7).min()
Value1B = hittersmean.loc[hittersmean['BestPos']=='1B']['value'].nlargest(7).min()
Value2B = hittersmean.loc[hittersmean['BestPos']=='2B']['value'].nlargest(7).min()
ValueSS = hittersmean.loc[hittersmean['BestPos']=='SS']['value'].nlargest(7).min()
Value3B = hittersmean.loc[hittersmean['BestPos']=='3B']['value'].nlargest(7).min()
ValueOF = hittersmean.loc[hittersmean['BestPos']=='OF']['value'].nlargest(20).min()
ValueUtil = max(Value1B,Value2B,ValueSS,Value3B,ValueOF,ValueC)

hittersmean.loc[hittersmean['BestPos'] == 'C', 'ReplacementValue'] = ValueC
hittersmean.loc[hittersmean['BestPos'] == '1B', 'ReplacementValue'] = ValueUtil
hittersmean.loc[hittersmean['BestPos'] == '2B', 'ReplacementValue'] = ValueUtil
hittersmean.loc[hittersmean['BestPos'] == 'SS', 'ReplacementValue'] = ValueUtil
hittersmean.loc[hittersmean['BestPos'] == '3B', 'ReplacementValue'] = ValueUtil
hittersmean.loc[hittersmean['BestPos'] == 'OF', 'ReplacementValue'] = ValueUtil
hittersmean.loc[hittersmean['BestPos'] == 'Util', 'ReplacementValue'] = ValueUtil

hittersmean['VORP']=hittersmean['value']-hittersmean['ReplacementValue']

In [270]:
hittersmean

,Team,ShortName,G,AB,PA,H,1B,2B,3B,HR,...,SLGOnTeam,OPSValue,AVGValue,value,Pos,BestPos,rank,utilrank,ReplacementValue,VORP
0,NYY,Yankees,144.9460,511.8710,637.1380,148.5080,76.22220,24.69210,1.008210,46.58520,...,0.454929,3.871930,9.524437,35.943620,[OF],OF,1.0,2.0,23.750184,12.193436
1,KCR,Royals,151.4330,598.9770,660.3630,174.4240,102.95600,36.72000,6.257720,28.49000,...,0.447473,1.462557,9.565959,31.658062,[SS],SS,1.0,4.0,23.750184,7.907878
2,LAD,Dodgers,148.3860,558.8900,659.8270,158.2230,79.61940,27.19000,5.114730,46.29930,...,0.454628,3.288766,9.279535,38.742877,[P],Util,1.0,1.0,23.750184,14.992693
3,NYM,Mets,154.5980,543.8930,677.6950,148.6610,84.16020,24.86700,1.005500,38.62780,...,0.448622,2.693714,8.951928,34.268553,[OF],OF,2.0,3.0,23.750184,10.518369
4,BAL,Orioles,152.5590,581.3360,659.3560,156.7990,93.46520,32.81950,4.197670,26.31650,...,0.443482,0.823582,8.785811,27.868619,[SS],SS,3.0,15.0,23.750184,4.118435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,CIN,Reds,25.7053,83.5565,89.4294,19.8554,14.04760,2.91753,0.104427,2.78584,...,0.439028,-0.285598,9.221083,2.727512,"[3B, 1B]",3B,85.0,459.0,23.750184,-21.022672
624,COL,Rockies,60.9278,207.6330,228.0380,51.9231,34.49750,10.54880,1.385180,5.49164,...,0.438311,-0.426900,8.969628,6.862800,"[OF, 1B]",1B,37.0,322.0,23.750184,-16.887384
625,KCR,Royals,31.1324,96.3296,107.9920,21.0277,13.62080,4.30266,0.794284,2.30997,...,0.438475,-0.391383,9.051575,2.806783,[OF],OF,145.0,453.0,23.750184,-20.943401
626,HOU,Astros,18.4386,60.7253,68.4107,12.9504,8.00483,2.43190,0.452595,2.06112,...,0.439236,-0.205758,9.200536,2.171910,[2B],2B,58.0,486.0,23.750184,-21.578274
627,MIA,Marlins,20.0111,74.6882,80.4315,17.3608,11.93010,2.99226,0.088148,2.35029,...,0.439052,-0.276261,9.225773,2.120668,NaN,Util,43.0,492.0,23.750184,-21.629516

In [271]:
atcpit.dtypes

Team           object
ShortName      object
W             float64
L             float64
GS            float64
G             float64
SV            float64
HLD           float64
BS            float64
IP            float64
TBF           float64
H             float64
R             float64
ER            float64
HR            float64
SO            float64
BB            float64
IBB           float64
HBP           float64
ERA           float64
WHIP          float64
K/9           float64
BB/9          float64
K/BB          float64
HR/9          float64
K%            float64
BB%           float64
K-BB%         float64
GB%           float64
AVG           float64
BABIP         float64
LOB%          float64
FIP           float64
FPTS          float64
FPTS_IP       float64
SPTS            int64
SPTS_IP       float64
WAR           float64
RA9-WAR       float64
InterSD       float64
InterSK       float64
IntraSD       float64
QS            float64
Vol           float64
Skew          float64
Dim           float64
ADP           float64
teamid          int64
League         object
PlayerName     object
xMLBAMID        int64
playerids      object
playerid       object
dtype: object

In [272]:

pitchersmean = atcpit.copy()

########################
#CHANGE THE COLUMNS BELOW BASED ON SGP VALUES FOR YOUR LEAGUE
#I think that you can use SGP based on MLB league averages
pitchersmean['ERA']=((525.55+pitchersmean['ER'])*9/(1350.0+pitchersmean['IP'])-3.5)/-0.106
pitchersmean['WHIP'] =((1620.0+pitchersmean['H']+pitchersmean['BB'])/(1350.0+pitchersmean['IP'])-1.2)/-0.02
pitchersmean['KBB'] = (((55*9+pitchersmean['SO'])/(55*3+pitchersmean['BB']))-3)/0.09
pitchersmean['value'] = pitchersmean['W'] / 7.0 + pitchersmean['ERA']+pitchersmean['WHIP']+(pitchersmean['SO']/50.0)+(pitchersmean['SV']+pitchersmean['HLD'])/10.0#######################

pitchersmean['Pos'] = pitchersmean['GS'].apply(lambda x: 'SP' if x > 10 else 'RP')
pitchersmean['rank'] = pitchersmean.groupby('Pos')['value'].rank(ascending=False)
RPValue = pitchersmean.loc[pitchersmean['Pos']=='RP']['value'].nlargest(10).min()
SPValue = pitchersmean.loc[pitchersmean['Pos']=='SP']['value'].nlargest(30).min()
pitchersmean.loc[pitchersmean['Pos'] == 'RP', 'ReplacementValue'] = RPValue
pitchersmean.loc[pitchersmean['Pos'] == 'SP', 'ReplacementValue'] = SPValue

pitchersmean['VORP']=pitchersmean['value']-pitchersmean['ReplacementValue']

In [273]:
pitchersmean

,Team,ShortName,W,L,GS,G,SV,HLD,BS,IP,...,PlayerName,xMLBAMID,playerids,playerid,KBB,value,Pos,rank,ReplacementValue,VORP
0,DET,Tigers,14.130000,6.58295,29.374000,29.3740,0.000000,0.000000,0.000000,188.1700,...,Tarik Skubal,669373,22267,22267,6.158753,8.869893,SP,1.0,4.317989,4.551903
1,PIT,Pirates,12.072700,7.79093,29.806200,29.8062,0.000000,0.000000,0.000000,184.2750,...,Paul Skenes,694973,33677,33677,4.400077,7.992408,SP,2.0,4.317989,3.674419
2,BOS,Red Sox,13.916700,8.00129,29.262600,29.2626,0.000000,0.000000,0.712044,183.1310,...,Garrett Crochet,676979,27463,27463,4.319209,7.800304,SP,3.0,4.317989,3.482315
3,SFG,Giants,13.225400,9.41404,29.882100,29.8821,0.000000,0.176178,0.000000,192.7720,...,Logan Webb,657277,17995,17995,2.654304,5.935989,SP,9.0,4.317989,1.618000
4,PHI,Phillies,11.913000,7.49325,29.244500,29.2445,0.000000,0.000000,0.000000,186.8790,...,Cristopher Sánchez,650911,20778,20778,2.285171,5.999545,SP,7.0,4.317989,1.681556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
839,BAL,Orioles,1.621390,2.25195,0.039116,48.8792,0.176788,12.431900,0.907362,52.3552,...,Rico Garcia,670329,20023,20023,-1.141463,1.819595,RP,154.0,5.381212,-3.561618
840,CHW,White Sox,2.052140,2.40378,0.000000,42.3131,0.023983,3.150770,0.314907,47.4470,...,Wikelman González,682790,26641,26641,-2.420093,0.609276,RP,329.0,5.381212,-4.771936
841,COL,Rockies,0.909821,2.44136,0.000000,28.7790,0.000000,1.333820,1.989840,28.4608,...,Luis Peralta,678821,24203,24203,-1.564081,-0.078442,RP,655.0,5.381212,-5.459654
842,ATH,Athletics,3.837780,4.14676,0.000000,56.6758,2.927450,10.438700,2.792360,59.3439,...,Michael Kelly,547184,12791,12791,-1.484276,2.047188,RP,132.0,5.381212,-3.334024
843,COL,Rockies,2.575420,3.82687,0.000000,53.5871,3.935160,7.067790,2.400070,56.0279,...,Zach Agnos,688642,31552,31552,-1.643001,1.174982,RP,237.0,5.381212,-4.206231

In [274]:
final=pd.concat([hittersmean,pitchersmean])

In [275]:
final['VORP']=final['VORP'].round(2)

In [276]:
final['PlayerName']=final['PlayerName'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [277]:
final.sort_values('VORP', ascending=False)

,Team,ShortName,G,AB,PA,H,1B,2B,3B,HR,...,HR/9,K-BB%,GB%,LOB%,FIP,FPTS_IP,SPTS_IP,RA9-WAR,QS,KBB
2,LAD,Dodgers,148.38600,558.8900,659.8270,158.22300,79.61940,27.190000,5.114730,46.299300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NYY,Yankees,144.94600,511.8710,637.1380,148.50800,76.22220,24.692100,1.008210,46.585200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NYM,Mets,154.59800,543.8930,677.6950,148.66100,84.16020,24.867000,1.005500,38.627800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,SEA,Mariners,150.13000,538.9910,624.5880,123.77300,61.09350,22.557800,0.297751,39.823500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,KCR,Royals,151.43300,598.9770,660.3630,174.42400,102.95600,36.720000,6.257720,28.490000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536,None,None,7.13210,18.9552,20.7110,4.65861,3.42167,0.835784,0.048812,0.352339,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
414,TOR,Blue Jays,5.98813,21.0492,22.9671,4.32205,3.26198,0.667732,0.018190,0.374154,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,CIN,Reds,8.40507,20.6434,21.7757,4.12580,3.18447,0.641234,0.014272,0.285826,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510,CHW,White Sox,9.59260,19.1561,20.5264,4.10017,2.84412,0.806365,0.052793,0.396889,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,WSN,Nationals,7.39711,21.4368,22.8313,4.93115,3.61304,1.117210,0.024329,0.176560,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final.sort_values('VORP', ascending=False).nlargest(300,['VORP']).to_csv("ATC.csv")

In [279]:
final[['PlayerName','Team','Pos','BestPos','G','GS','W','SV','ERA','WHIP','KBB','value','VORP','ADP','rank','utilrank']].sort_values('VORP', ascending=False).nlargest(300,['VORP']).round(2).to_csv("draft.csv", sep=",")

In [280]:
final['VORP'].describe()

count    1472.000000
mean       -7.820231
std         7.335054
min       -23.390000
25%       -12.885000
50%        -5.040000
75%        -3.130000
max        14.990000
Name: VORP, dtype: float64