In [4]:
import pandas as pd
import numpy as np

In [5]:
import sys
sys.path.append('../')

In [6]:
def GetPosition (array):
    if isinstance(array,np.ndarray):
        if array.__contains__('C'):
            return 'C'
        if array.__contains__('2B'):
            return '2B'
        if array.__contains__('3B'):
            return '3B'
        if array.__contains__('SS'):
            return 'SS'
        if array.__contains__('1B'):
            return '1B'
        if array.__contains__('OF'):
            return 'OF'
        else:
            return 'Util'
    else: 
        return 'Util'

In [7]:
atcpit=pd.read_json('https://www.fangraphs.com/api/projections?stats=pit&type=atc')
atcbat=pd.read_json('https://www.fangraphs.com/api/projections?stats=bat&type=atc')

In [8]:
atcbat

,Team,ShortName,G,AB,PA,H,1B,2B,3B,HR,...,ADP,Pos,minpos,UPURL,teamid,League,PlayerName,xMLBAMID,playerids,playerid
0,NYY,Yankees,144.7050,513.873,635.036,145.3750,74.2669,24.56290,0.509115,46.03650,...,3.170000,0.257862,OF,/players/aaron-judge/15640/stats?position=OF,9,AL,Aaron Judge,592450,15640,15640
1,KCR,Royals,151.2370,597.958,658.627,175.9860,103.3720,34.99770,7.672040,29.94460,...,1.700000,0.006211,SS,/players/bobby-witt-jr/25764/stats?position=SS,7,AL,Bobby Witt Jr.,677951,25764,25764
2,BAL,Orioles,147.7090,567.259,646.005,153.8380,87.9572,29.61240,5.555650,30.71320,...,8.180000,0.012579,3B/SS,/players/gunnar-henderson/26289/stats?position...,2,AL,Gunnar Henderson,683002,26289,26289
3,NYM,Mets,151.9490,533.098,669.106,146.7330,83.1276,27.13970,2.156080,34.30990,...,7.420000,0.032051,OF,/players/juan-soto/20123/stats?position=OF,25,NL,Juan Soto,665742,20123,20123
4,LAD,Dodgers,145.3430,553.369,642.998,158.5270,82.9524,29.13200,5.123590,41.31870,...,1.480000,1.000000,DH,/players/shohei-ohtani/19755/stats?position=DH,22,NL,Shohei Ohtani,660271,19755,19755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
641,COL,Rockies,46.6766,166.576,184.876,38.7163,25.7376,7.53139,0.958063,4.48930,...,999.000000,0.000000,OF,/players/zachary-veen/sa3014516/stats?position=OF,19,NL,Zac Veen,691728,sa3014516,sa3014516
642,COL,Rockies,94.0245,352.969,397.397,86.0669,57.9664,16.99590,0.664205,10.44030,...,520.469971,0.405405,3B/OF,/players/kris-bryant/15429/stats?position=3B/OF,19,NL,Kris Bryant,592178,15429,15429
643,MIA,Marlins,87.9967,314.782,349.151,65.7280,41.0761,12.73010,1.011120,10.91060,...,648.419983,0.038462,OF,/players/griffin-conine/21626/stats?position=OF,20,NL,Griffin Conine,665052,21626,21626
644,MIA,Marlins,85.4334,296.331,329.285,62.8707,38.7669,13.43980,0.644282,10.01970,...,583.549988,0.800000,1B,/players/matt-mervis/27845/stats?position=1B,20,NL,Matt Mervis,670223,27845,27845
645,KCR,Royals,64.1347,222.319,257.543,53.8115,37.8889,10.65440,0.378430,4.88976,...,632.950012,0.265625,OF,/players/mark-canha/11445/stats?position=OF,7,AL,Mark Canha,592192,11445,11445

In [9]:
import pybaseball
positions = pybaseball.fielding_stats(2024, qual=0)
positions['Pos']=positions['Pos'].replace(['LF','CF','RF'],'OF')
positions_unique=positions.loc[(positions['G']>=10) | (positions['GS']>=5)].groupby('IDfg')['Pos'].unique()

In [10]:
positions

,IDfg,Season,Name,Team,Pos,G,GS,Inn,PO,A,...,60-90%,# 60-90%,90-100%,# 90-100%,rSZ,rCERA,rTS,FRM,OAA,Range
0,27478,2024,Patrick Bailey,SFG,C,115,101,908.0,904,55,...,NaN,NaN,NaN,NaN,15.0,1.0,NaN,23.7,NaN,NaN
1,21534,2024,Cal Raleigh,SEA,C,135,125,1122.0,1138,51,...,NaN,NaN,NaN,NaN,11.0,3.0,NaN,12.9,NaN,NaN
2,19452,2024,Jake Rogers,DET,C,92,86,761.0,744,29,...,NaN,NaN,NaN,NaN,9.0,2.0,NaN,13.6,NaN,NaN
3,22581,2024,Alejandro Kirk,TOR,C,93,89,766.0,706,46,...,NaN,NaN,NaN,NaN,7.0,-1.0,NaN,9.2,NaN,NaN
4,27562,2024,Austin Wells,NYY,C,110,96,872.1,892,33,...,NaN,NaN,NaN,NaN,7.0,0.0,NaN,10.5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2231,33828,2024,Naoyuki Uwasawa,BOS,P,2,0,4.0,1,0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN
2232,33829,2024,Shota Imanaga,CHC,P,29,29,173.1,4,14,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,-1.0,NaN,NaN
2233,33834,2024,Andrew Walters,CLE,P,9,1,8.2,1,0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.1,NaN,NaN
2234,33838,2024,Yariel Rodriguez,TOR,P,21,21,86.2,8,7,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.2,NaN,NaN
2235,33876,2024,Rhett Lowder,CIN,P,6,6,30.2,1,1,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.1,NaN,NaN

In [11]:
positions_unique.index=positions_unique.index.map(str)

In [12]:
hittersmean=pd.merge(atcbat,positions_unique,how='left',left_on='playerids',right_index=True)

hittersmean['OBPOnTeam'] = (hittersmean['PA']*hittersmean['OBP']+2037.4)/(hittersmean['PA']+6100)
hittersmean['SLGOnTeam'] = (hittersmean['AB']*hittersmean['SLG']+2420)/(hittersmean['AB']+5500)
hittersmean['OPSValue'] = (hittersmean['OBPOnTeam']+hittersmean['SLGOnTeam']-.774)/.006

hittersmean['AVGValue'] = ((hittersmean['H']+1768)/(hittersmean['AB']+6100)-.267)/.0024
hittersmean['value'] = hittersmean['OPSValue']+(hittersmean['R']/8.92+hittersmean['HR']/7.5+hittersmean['RBI']/8.92+hittersmean['SB']/7.0)

hittersmean['Pos']=hittersmean['Pos_y']

hittersmean['BestPos']=hittersmean['Pos'].apply(GetPosition)

hittersmean['rank']=hittersmean.groupby('BestPos')['value'].rank(ascending=False)
hittersmean['utilrank']=hittersmean['value'].rank(ascending=False)

ValueC = hittersmean.loc[hittersmean['BestPos']=='C']['value'].nlargest(8).min()
Value1B = hittersmean.loc[hittersmean['BestPos']=='1B']['value'].nlargest(6).min()
Value2B = hittersmean.loc[hittersmean['BestPos']=='2B']['value'].nlargest(7).min()
ValueSS = hittersmean.loc[hittersmean['BestPos']=='SS']['value'].nlargest(10).min()
Value3B = hittersmean.loc[hittersmean['BestPos']=='3B']['value'].nlargest(8).min()
ValueOF = hittersmean.loc[hittersmean['BestPos']=='OF']['value'].nlargest(20).min()
ValueUtil = max(Value1B,Value2B,ValueSS,Value3B,ValueOF,ValueC)

hittersmean.loc[hittersmean['BestPos'] == 'C', 'ReplacementValue'] = ValueC
hittersmean.loc[hittersmean['BestPos'] == '1B', 'ReplacementValue'] = Value1B
hittersmean.loc[hittersmean['BestPos'] == '2B', 'ReplacementValue'] = Value2B
hittersmean.loc[hittersmean['BestPos'] == 'SS', 'ReplacementValue'] = ValueSS
hittersmean.loc[hittersmean['BestPos'] == '3B', 'ReplacementValue'] = Value3B
hittersmean.loc[hittersmean['BestPos'] == 'OF', 'ReplacementValue'] = ValueOF
hittersmean.loc[hittersmean['BestPos'] == 'Util', 'ReplacementValue'] = ValueUtil

hittersmean['VORP']=hittersmean['value']-hittersmean['ReplacementValue']

In [24]:
atcpit.dtypes

Team           object
ShortName      object
W             float64
L             float64
GS            float64
G             float64
SV            float64
HLD           float64
BS            float64
IP            float64
TBF           float64
H             float64
R             float64
ER            float64
HR            float64
SO            float64
BB            float64
IBB           float64
HBP           float64
ERA           float64
WHIP          float64
K/9           float64
BB/9          float64
K/BB          float64
HR/9          float64
K%            float64
BB%           float64
K-BB%         float64
GB%           float64
AVG           float64
BABIP         float64
LOB%          float64
FIP           float64
FPTS          float64
FPTS_IP       float64
SPTS            int64
SPTS_IP       float64
WAR           float64
RA9-WAR       float64
InterSD       float64
InterSK       float64
IntraSD       float64
QS            float64
Vol           float64
Skew          float64
Dim           float64
ADP           float64
teamid          int64
League         object
PlayerName     object
xMLBAMID        int64
playerids      object
playerid       object
dtype: object

In [26]:

pitchersmean = atcpit.copy()

########################
#CHANGE THE COLUMNS BELOW BASED ON SGP VALUES FOR YOUR LEAGUE
#I think that you can use SGP based on MLB league averages
pitchersmean['ERA']=((525.55+pitchersmean['ER'])*9/(1350.0+pitchersmean['IP'])-3.5)/-0.106
pitchersmean['WHIP'] =((1620.0+pitchersmean['H']+pitchersmean['BB'])/(1350.0+pitchersmean['IP'])-1.2)/-0.02
pitchersmean['KBB'] = (((55*9+pitchersmean['SO'])/(55*3+pitchersmean['BB']))-3)/0.09
pitchersmean['value'] = pitchersmean['KBB']+pitchersmean['ERA']+pitchersmean['WHIP']+(pitchersmean['K/9']*pitchersmean['IP']/40.0+(pitchersmean['SV']+pitchersmean['HLD'])/10.0)
########################

pitchersmean['Pos'] = pitchersmean['GS'].apply(lambda x: 'SP' if x > 1 else 'RP')
pitchersmean['rank'] = pitchersmean.groupby('Pos')['value'].rank(ascending=False)
RPValue = pitchersmean.loc[pitchersmean['Pos']=='RP']['value'].nlargest(20).min()
SPValue = pitchersmean.loc[pitchersmean['Pos']=='SP']['value'].nlargest(40).min()
pitchersmean.loc[pitchersmean['Pos'] == 'RP', 'ReplacementValue'] = RPValue
pitchersmean.loc[pitchersmean['Pos'] == 'SP', 'ReplacementValue'] = SPValue

pitchersmean['VORP']=pitchersmean['value']-pitchersmean['ReplacementValue']

In [27]:
pitchersmean

,Team,ShortName,W,L,GS,G,SV,HLD,BS,IP,...,PlayerName,xMLBAMID,playerids,playerid,KBB,value,Pos,rank,ReplacementValue,VORP
0,PIT,Pirates,12.035600,6.467580,29.258700,29.2587,0.000000,0.00000,0.000000,173.6790,...,Paul Skenes,694973,33677,33677,3.946807,54.251259,SP,2.0,37.755987,16.495272
1,DET,Tigers,13.996000,7.185910,29.462000,29.4620,0.000000,0.00000,0.000000,183.8000,...,Tarik Skubal,669373,22267,22267,5.269023,55.210543,SP,1.0,37.755987,17.454557
2,PHI,Phillies,14.086100,8.052860,30.071500,30.0715,0.000000,0.00000,0.000000,192.2040,...,Zack Wheeler,554430,10310,10310,3.204018,50.525298,SP,3.0,37.755987,12.769311
3,SFG,Giants,12.747200,9.893140,30.402100,30.4021,0.000000,0.00000,0.000000,196.5150,...,Logan Webb,657277,17995,17995,1.837841,39.739802,SP,29.0,37.755987,1.983815
4,BOS,Red Sox,11.101300,7.238630,29.415400,29.4154,0.000000,0.00000,1.023270,152.8520,...,Garrett Crochet,676979,27463,27463,3.511967,49.162150,SP,5.0,37.755987,11.406163
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,CHW,White Sox,1.587220,2.637980,0.000000,32.4666,0.000000,6.31414,1.274980,33.8451,...,Steven Wilson,621051,20353,20353,-1.269993,6.349456,RP,268.0,20.674768,-14.325312
881,PIT,Pirates,0.453853,1.158770,0.000000,33.6636,2.929520,1.60220,1.629730,35.6527,...,Tanner Rainey,663432,17610,17610,-1.307725,5.607741,RP,298.0,20.674768,-15.067027
882,ATH,Athletics,2.364410,2.690510,0.260391,26.4899,0.026836,0.00000,0.441657,32.8509,...,Anthony Maldonado,687424,26034,26034,-1.212415,4.590518,RP,341.0,20.674768,-16.084250
883,ATL,Braves,1.261600,0.691978,0.000000,27.8773,0.000000,2.79787,1.096080,31.2282,...,Jordan Weems,607179,13190,13190,-1.007178,5.142378,RP,323.0,20.674768,-15.532390
884,ARI,Diamondbacks,1.491020,1.791620,0.000000,37.0618,0.030514,2.76875,0.000000,46.1954,...,Bryce Jarvis,686826,27477,27477,-2.083220,5.095012,RP,324.0,20.674768,-15.579755

In [28]:
final=pd.concat([hittersmean,pitchersmean])

In [29]:
final['VORP']=final['VORP'].round(2)

In [17]:
final['PlayerName']=final['PlayerName'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [30]:
final.sort_values('VORP', ascending=False)

,Team,ShortName,G,AB,PA,H,1B,2B,3B,HR,...,HR/9,K-BB%,GB%,LOB%,FIP,FPTS_IP,SPTS_IP,RA9-WAR,QS,KBB
1,DET,Tigers,29.46200,NaN,NaN,145.47600,NaN,NaN,NaN,17.353900,...,0.849754,0.240631,NaN,0.751873,2.81793,5.790761,5.375000,5.164180,15.694600,5.269023
0,PIT,Pirates,29.25870,NaN,NaN,134.25300,NaN,NaN,NaN,14.360000,...,0.744133,0.244105,NaN,0.761953,2.68331,5.959770,5.505747,5.580360,15.219600,3.946807
4,LAD,Dodgers,145.34300,553.369,642.998,158.52700,82.9524,29.1320,5.123590,41.318700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NYY,Yankees,144.70500,513.873,635.036,145.37500,74.2669,24.5629,0.509115,46.036500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PHI,Phillies,30.07150,NaN,NaN,157.73600,NaN,NaN,NaN,21.049100,...,0.985629,0.203849,NaN,0.735623,3.32673,5.185938,4.848958,4.610460,17.942800,3.204018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,ATH,Athletics,1.58150,NaN,NaN,6.32907,NaN,NaN,NaN,0.907846,...,1.237640,0.109966,NaN,0.699218,4.60856,3.842857,3.571429,0.022777,0.400165,-0.141895
847,None,None,2.78533,NaN,NaN,12.67130,NaN,NaN,NaN,2.331520,...,1.733240,0.043685,NaN,0.700848,5.97851,2.033333,2.333333,-0.077651,0.487159,-0.710344
593,ATL,Braves,1.33146,NaN,NaN,6.43843,NaN,NaN,NaN,0.734928,...,1.028850,0.088501,NaN,0.695267,4.54618,2.916667,3.000000,-0.016501,0.511523,-0.213358
720,CHW,White Sox,2.63070,NaN,NaN,7.67383,NaN,NaN,NaN,1.122670,...,1.310490,0.063232,NaN,0.700899,5.12723,3.262500,3.375000,-0.026228,0.163945,-0.357927
691,CHW,White Sox,1.21852,NaN,NaN,5.50810,NaN,NaN,NaN,0.875510,...,1.405160,0.071307,NaN,0.684616,5.30062,2.916667,3.000000,-0.022595,0.239513,-0.273059

In [19]:
final.sort_values('VORP', ascending=False).nlargest(200,['VORP']).to_csv("ATC.csv")

In [22]:
final[['PlayerName','Team','Pos','BestPos','G','GS','W','SV','ERA','WHIP','KBB','value','VORP','ADP','rank','utilrank']].sort_values('VORP', ascending=False).nlargest(300,['VORP']).round(2).to_csv("draft.csv", sep=",")

In [21]:
final

,Team,ShortName,G,AB,PA,H,1B,2B,3B,HR,...,HR/9,K-BB%,GB%,LOB%,FIP,FPTS_IP,SPTS_IP,RA9-WAR,QS,KBB
0,NYY,Yankees,144.7050,513.873,635.036,145.3750,74.2669,24.5629,0.509115,46.03650,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,KCR,Royals,151.2370,597.958,658.627,175.9860,103.3720,34.9977,7.672040,29.94460,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BAL,Orioles,147.7090,567.259,646.005,153.8380,87.9572,29.6124,5.555650,30.71320,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NYM,Mets,151.9490,533.098,669.106,146.7330,83.1276,27.1397,2.156080,34.30990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LAD,Dodgers,145.3430,553.369,642.998,158.5270,82.9524,29.1320,5.123590,41.31870,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,CHW,White Sox,32.4666,NaN,NaN,28.7382,NaN,NaN,NaN,5.86271,...,1.55899,0.104609,NaN,0.699779,5.22525,3.952941,3.647059,-0.234672,0.0,-1.269993
881,PIT,Pirates,33.6636,NaN,NaN,34.5994,NaN,NaN,NaN,5.89619,...,1.48841,0.088905,NaN,0.716147,5.19302,3.572222,3.583333,-0.163553,0.0,-1.307725
882,ATH,Athletics,26.4899,NaN,NaN,33.6044,NaN,NaN,NaN,5.99535,...,1.64252,0.087888,NaN,0.727578,5.25625,2.787879,2.939394,-0.286854,0.0,-1.212415
883,ATL,Braves,27.8773,NaN,NaN,29.6674,NaN,NaN,NaN,5.03630,...,1.45147,0.101108,NaN,0.671896,5.01125,3.512903,3.516129,-0.258021,0.0,-1.007178
884,ARI,Diamondbacks,37.0618,NaN,NaN,44.4544,NaN,NaN,NaN,5.73319,...,1.11697,0.052815,NaN,0.732961,4.96740,3.417391,3.413043,0.050425,0.0,-2.083220