In [23]:
import pandas as pd
import numpy as np
import json
import requests

In [24]:
import sys
sys.path.append('../')

In [25]:
def GetPosition (array):
    if isinstance(array,np.ndarray):
        if array.__contains__('C'):
            return 'C'
        if array.__contains__('2B'):
            return '2B'
        if array.__contains__('3B'):
            return '3B'
        if array.__contains__('SS'):
            return 'SS'
        if array.__contains__('1B'):
            return '1B'
        if array.__contains__('OF'):
            return 'OF'
        else:
            return 'Util'
    else: 
        return 'Util'

In [26]:
atcpit=pd.read_json('https://www.fangraphs.com/api/projections?stats=pit&type=atc')
atcbat=pd.read_json('https://www.fangraphs.com/api/projections?stats=bat&type=atc')

In [27]:
atcbat

,Team,ShortName,G,AB,PA,H,1B,2B,3B,HR,...,ADP,Pos,minpos,UPURL,teamid,League,PlayerName,xMLBAMID,playerids,playerid
0,NYY,Yankees,145.7960,517.0230,638.9010,146.2140,74.97910,24.45230,0.511426,46.27110,...,3.160000,0.257862,OF,/players/aaron-judge/15640/stats?position=OF,9,AL,Aaron Judge,592450,15640,15640
1,KCR,Royals,153.2550,606.0880,667.2580,178.1470,104.84500,35.42680,7.769930,30.10490,...,1.620000,0.006211,SS,/players/bobby-witt-jr/25764/stats?position=SS,7,AL,Bobby Witt Jr.,677951,25764,25764
2,BAL,Orioles,147.6950,566.6640,645.2770,153.3880,87.85920,29.53900,5.546390,30.44390,...,7.660000,0.012579,3B/SS,/players/gunnar-henderson/26289/stats?position...,2,AL,Gunnar Henderson,683002,26289,26289
3,NYM,Mets,152.9770,536.7690,673.7470,147.5890,83.63950,27.29240,2.169360,34.48760,...,7.520000,0.032051,OF,/players/juan-soto/20123/stats?position=OF,25,NL,Juan Soto,665742,20123,20123
4,LAD,Dodgers,145.4880,554.0480,643.6750,158.5970,82.99190,29.13270,5.148270,41.32460,...,1.530000,1.000000,DH,/players/shohei-ohtani/19755/stats?position=DH,22,NL,Shohei Ohtani,660271,19755,19755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,COL,Rockies,102.5860,359.6470,396.6260,85.0638,54.86570,18.83090,1.696430,9.67071,...,393.049988,0.000000,OF,/players/jordan-beck/31431/stats?position=OF,19,NL,Jordan Beck,687597,31431,31431
628,ATH,Athletics,17.9121,45.2522,49.7022,10.2649,7.26726,1.35155,0.000000,1.64613,...,999.000000,0.120000,C,/players/kyle-mccann/25575/stats?position=C,10,AL,Kyle McCann,668832,25575,25575
629,COL,Rockies,97.3214,366.2240,412.3190,89.1728,60.05580,17.61870,0.687267,10.81090,...,506.739990,0.405405,3B/OF,/players/kris-bryant/15429/stats?position=3B/OF,19,NL,Kris Bryant,592178,15429,15429
630,MIA,Marlins,83.3493,293.8600,326.0090,61.2503,38.58880,11.69160,0.996783,9.97320,...,675.549988,0.038462,OF,/players/griffin-conine/21626/stats?position=OF,20,NL,Griffin Conine,665052,21626,21626
631,MIA,Marlins,84.7192,293.9010,326.7630,62.3140,38.57700,13.16240,0.663178,9.91144,...,581.159973,0.800000,1B,/players/matt-mervis/27845/stats?position=1B,20,NL,Matt Mervis,670223,27845,27845

In [28]:
hittersmean = atcbat
pitchersmean = atcpit

In [29]:
hittersmean['OBPOnTeam'] = (hittersmean['PA']*hittersmean['OBP']+2037.4)/(hittersmean['PA']+6100)
hittersmean['SLGOnTeam'] = (hittersmean['AB']*hittersmean['SLG']+2420)/(hittersmean['AB']+5500)
hittersmean['OPSValue'] = (hittersmean['OBPOnTeam']+hittersmean['SLGOnTeam']-.774)/.006

hittersmean['AVGValue'] = ((hittersmean['H']+1768)/(hittersmean['AB']+6100)-.267)/.0024
hittersmean['value'] = hittersmean['OPSValue']+(hittersmean['R']/8.92+hittersmean['HR']/7.5+hittersmean['RBI']/8.92+hittersmean['SB']/6.0)

In [30]:
import pybaseball
positions = pybaseball.fielding_stats(2024, qual=0)

In [31]:
positions['Pos']=positions['Pos'].replace(['LF','CF','RF'],'OF')

In [32]:
positions_unique=positions.loc[(positions['G']>=10) | (positions['GS']>=5)].groupby('IDfg')['Pos'].unique()

In [33]:
positions

,IDfg,Season,Name,Team,Pos,G,GS,Inn,PO,A,...,60-90%,# 60-90%,90-100%,# 90-100%,rSZ,rCERA,rTS,FRM,OAA,Range
0,27478,2024,Patrick Bailey,SFG,C,115,101,908.0,904,55,...,NaN,NaN,NaN,NaN,15,1.0,NaN,23.7,NaN,NaN
1,21534,2024,Cal Raleigh,SEA,C,135,125,1122.0,1138,51,...,NaN,NaN,NaN,NaN,11,3.0,NaN,12.9,NaN,NaN
2,19452,2024,Jake Rogers,DET,C,92,86,761.0,744,29,...,NaN,NaN,NaN,NaN,9,2.0,NaN,13.6,NaN,NaN
3,22581,2024,Alejandro Kirk,TOR,C,93,89,766.0,706,46,...,NaN,NaN,NaN,NaN,7,-1.0,NaN,9.2,NaN,NaN
4,27562,2024,Austin Wells,NYY,C,110,96,872.1,892,33,...,NaN,NaN,NaN,NaN,7,0.0,NaN,10.5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2231,33828,2024,Naoyuki Uwasawa,BOS,P,2,0,4.0,1,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN
2232,33829,2024,Shota Imanaga,CHC,P,29,29,173.1,4,14,...,NaN,NaN,NaN,NaN,1,NaN,NaN,-1.0,NaN,NaN
2233,33834,2024,Andrew Walters,CLE,P,9,1,8.2,1,0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0.1,NaN,NaN
2234,33838,2024,Yariel Rodriguez,TOR,P,21,21,86.2,8,7,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0.2,NaN,NaN
2235,33876,2024,Rhett Lowder,CIN,P,6,6,30.2,1,1,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0.1,NaN,NaN

In [34]:
positions_unique.index=positions_unique.index.map(str)

In [35]:
hitterspos=pd.merge(hittersmean,positions_unique,how='left',left_on='playerids',right_index=True)

In [36]:
hitterspos['Pos']=hitterspos['Pos_y']

In [37]:
hitterspos['BestPos']=hitterspos['Pos'].apply(GetPosition)

hitterspos['rank']=hitterspos.groupby('BestPos')['value'].rank(ascending=False)
hitterspos['utilrank']=hitterspos['value'].rank(ascending=False)

###customized league replacement value
replacementvalue=hitterspos.groupby('BestPos').value.nlargest(8).groupby('BestPos').min().reset_index(name='PosValue')
replacementvalue['UtilValue']=float(hitterspos.loc[hitterspos['utilrank']==64]['value'])

replacementvalue['ReplacementValue']=pd.DataFrame([replacementvalue['UtilValue'], replacementvalue['PosValue']]).min()
#replacementvalue['ReplacementValue']=replacementvalue['UtilValue']
replacementvalue.loc[replacementvalue['BestPos'] == 'Util', 'ReplacementValue'] = replacementvalue['UtilValue']

/tmp/ipykernel_236753/3997149529.py:8: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  replacementvalue['UtilValue']=float(hitterspos.loc[hitterspos['utilrank']==64]['value'])

In [38]:
hittersmean[hittersmean['PlayerName']=='Bryce Harper']

,Team,ShortName,G,AB,PA,H,1B,2B,3B,HR,...,League,PlayerName,xMLBAMID,playerids,playerid,OBPOnTeam,SLGOnTeam,OPSValue,AVGValue,value
25,PHI,Phillies,145.409,540.607,631.621,149.86,87.138,34.1147,0.917373,27.69,...,NL,Bryce Harper,547180,11579,11579,0.337691,0.445134,1.47084,9.08664,26.668968

In [39]:
replacementvalue

  BestPos   PosValue  UtilValue  ReplacementValue
0      1B  20.962431  21.120158         20.962431
1      2B  19.194590  21.120158         19.194590
2      3B  21.730066  21.120158         21.120158
3       C  17.926802  21.120158         17.926802
4      OF  27.472286  21.120158         21.120158
5      SS  23.396620  21.120158         21.120158
6    Util  12.121140  21.120158         21.120158

In [40]:
hittersfinal=hitterspos.reset_index().merge(replacementvalue,on='BestPos',how='left')

hittersfinal['VORP']=hittersfinal['value']-hittersfinal['ReplacementValue']

In [41]:
pitchersmean.columns

Index(['Team', 'ShortName', 'W', 'L', 'GS', 'G', 'SV', 'HLD', 'BS', 'IP',
       'TBF', 'H', 'R', 'ER', 'HR', 'SO', 'BB', 'IBB', 'HBP', 'ERA', 'WHIP',
       'K/9', 'BB/9', 'K/BB', 'HR/9', 'K%', 'BB%', 'K-BB%', 'GB%', 'AVG',
       'BABIP', 'LOB%', 'FIP', 'FPTS', 'FPTS_IP', 'SPTS', 'SPTS_IP', 'WAR',
       'RA9-WAR', 'InterSD', 'InterSK', 'IntraSD', 'QS', 'Vol', 'Skew', 'Dim',
       'ADP', 'teamid', 'League', 'PlayerName', 'xMLBAMID', 'playerids',
       'playerid'],
      dtype='object')

In [42]:

########################
#CHANGE THE COLUMNS BELOW BASED ON SGP VALUES FOR YOUR LEAGUE
#I think that you can use SGP based on MLB league averages
pitchersmean['ERA']=((525.55+pitchersmean['ER'])*9/(1350.0+pitchersmean['IP'])-3.5)/-0.106
pitchersmean['WHIP'] =((1620.0+pitchersmean['H']+pitchersmean['BB'])/(1350.0+pitchersmean['IP'])-1.2)/-0.02
pitchersmean['KBB'] = (((55*9+pitchersmean['SO'])/(55*3+pitchersmean['BB']))-3)/0.09
pitchersmean['value'] = pitchersmean['KBB']+pitchersmean['ERA']+pitchersmean['WHIP']+(pitchersmean['W']/4.05+(pitchersmean['SV']+pitchersmean['HLD'])/10.0)
########################

pitchersmean['utilrank']=pitchersmean['value'].rank(ascending=False)

###customized league replacement value
pitchersmean['ReplacementValue']=float(pitchersmean.loc[pitchersmean['utilrank']==80]['value'])

pitchersmean['VORP']=pitchersmean['value']-pitchersmean['ReplacementValue']

/tmp/ipykernel_236753/2023090372.py:13: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  pitchersmean['ReplacementValue']=float(pitchersmean.loc[pitchersmean['utilrank']==80]['value'])

In [43]:
pitchersmean['BB']

0      47.4246
1      38.9189
2      48.2877
3      44.6700
4      43.9630
        ...
886    37.9468
887    17.8892
888    15.0955
889    18.8902
890    24.1455
Name: BB, Length: 891, dtype: float64

In [44]:
final=pd.concat([hittersfinal,pitchersmean])

In [45]:
final['VORP']=final['VORP'].round(2)

In [46]:
final['PlayerName']=final['PlayerName'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [47]:
final.sort_values('VORP', ascending=False)

,index,Team,ShortName,G,AB,PA,H,1B,2B,3B,...,HR/9,K-BB%,GB%,LOB%,FIP,FPTS_IP,SPTS_IP,RA9-WAR,QS,KBB
4,4.0,LAD,Dodgers,145.48800,554.0480,643.6750,158.59700,82.99190,29.132700,5.148270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0.0,NYY,Yankees,145.79600,517.0230,638.9010,146.21400,74.97910,24.452300,0.511426,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,KCR,Royals,153.25500,606.0880,667.2580,178.14700,104.84500,35.426800,7.769930,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18.0,CIN,Reds,149.87600,579.6150,647.6810,147.11100,84.68390,30.729600,7.409980,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7.0,CLE,Guardians,152.56800,589.7660,661.8580,161.55500,92.82140,36.204500,3.287360,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,521.0,SDP,Padres,7.79057,22.5994,24.4371,4.92244,3.75137,0.813899,0.031106,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
561,561.0,ATH,Athletics,7.32776,21.0671,22.3431,4.46469,3.26076,0.718317,0.045847,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,518.0,PHI,Phillies,7.10422,19.8653,22.3965,4.54947,3.25798,1.000750,0.033360,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,336.0,SDP,Padres,9.66707,24.0451,26.4265,4.60587,3.22601,1.026250,0.080186,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540,540.0,TEX,Rangers,7.86819,23.2380,25.2867,5.14251,3.99164,0.927355,0.037194,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
final.sort_values('VORP', ascending=False).nlargest(200,['VORP']).to_csv("ATC.csv")

In [49]:
final[['PlayerName','Team','Pos','BestPos','G','GS','W','SV','ERA','WHIP','KBB','value','VORP','ADP','rank','utilrank']].sort_values('VORP', ascending=False).nlargest(200,['VORP']).round(2).to_csv("draft.csv", sep=",")